apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-docker.fullname" . }}
  labels:
    {{- include "springboot-docker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      appProtocol: mysql
      name: database
  selector:
    {{- include "springboot-docker.selectorLabels" . | nindent 4 }}
